### ISSUE TITLE
Missing build resources (affects runtime!)

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/trekarta#89]
Somewhere before the VTM update building broke here - probably the new 3D building update?

Current head builds, but the app crashes (in the emulator) - I did wipe data on the image, clean, rebuild everything in the app. Is it my configuration?

I have to checkout commit 094420a6cc1ea216c9d2aa24a44b0419240f3e00 (tag: 2019.09fix1), just before "amenities can be tapped" commit to get a running app.

Logcat gives this error - maybe you can tell something from this?

```
Launching 'app' on Unihertz Atom.
$ adb shell am start -n "mobi.maptrek/mobi.maptrek.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 4021 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/MapTrek: mobi.maptrek.MapTrek Has SD card: null
I/TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.
    Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.
E/MapTrek: mobi.maptrek.MainActivity ES: null
    mobi.maptrek.MainActivity New ES: null
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mobi.maptrek, PID: 4021
    java.lang.ExceptionInInitializerError
        at com.ibm.icu.text.IDNA.getUTS46Instance(IDNA.java:153)
        at mobi.maptrek.maps.maptrek.MapTrekDatabaseHelper.<clinit>(MapTrekDatabaseHelper.java:309)
        at mobi.maptrek.MapTrek.getDetailedMapDatabase(MapTrek.java:243)
        at mobi.maptrek.MapTrek.getMapIndex(MapTrek.java:303)
        at mobi.maptrek.MainActivity.onCreate(MainActivity.java:456)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.util.MissingResourceException: could not locate data 
        at com.ibm.icu.impl.ICUData.getStream(ICUData.java:143)
        at com.ibm.icu.impl.ICUBinary.getData(ICUBinary.java:496)
        at com.ibm.icu.impl.ICUBinary.getRequiredData(ICUBinary.java:450)
        at com.ibm.icu.impl.Normalizer2Impl.load(Normalizer2Impl.java:510)
        at com.ibm.icu.impl.Norm2AllModes$1.createInstance(Norm2AllModes.java:349)
        at com.ibm.icu.impl.Norm2AllModes$1.createInstance(Norm2AllModes.java:344)
        at com.ibm.icu.impl.SoftCache.getInstance(SoftCache.java:69)
        at com.ibm.icu.impl.Norm2AllModes.getInstance(Norm2AllModes.java:341)
        at com.ibm.icu.text.Normalizer2.getInstance(Normalizer2.java:202)
        at com.ibm.icu.impl.UTS46.<clinit>(UTS46.java:69)
        at com.ibm.icu.text.IDNA.getUTS46Instance(IDNA.java:153) 
        at mobi.maptrek.maps.maptrek.MapTrekDatabaseHelper.<clinit>(MapTrekDatabaseHelper.java:309) 
        at mobi.maptrek.MapTrek.getDetailedMapDatabase(MapTrek.java:243) 
        at mobi.maptrek.MapTrek.getMapIndex(MapTrek.java:303) 
        at mobi.maptrek.MainActivity.onCreate(MainActivity.java:456) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Process 4021 terminated.
```

**Comment by andreynovikov** [comment]
No, it's about https://github.com/andreynovikov/trekarta/commit/eff2692dbfb9db999c903b743893348646ff1752 and `com.ibm.icu` package. Looks like I forgot to commit some supplementary files. Will fix it tonight.

**Comment by andreynovikov** [comment]
Should also remove https://github.com/andreynovikov/trekarta/blob/master/icu-refs_heads_master-android_icu4j-src-main-java.tar.gz (added by mistake).

**Comment by hungerburg** [comment]
Still no luck, commit d511d7979ee54c664d30f47e15c8e6ff7b1e6022 introduced `(Parameters.THREADED_INIT)`, but its not defined anywhere

**Comment by hungerburg** [comment]
I see, build passes now, meanwhile could look at the other changes, stippling etc. :)
